#!/usr/bin/env bash
#
# sync-upstream.sh
#
# Mirrors specific files/paths from an upstream GitHub repo into
# vendor/upstream/ WITHOUT ever doing a manual clone-and-copy-paste.
# This is the only script that is allowed to write into vendor/upstream/.
#
# It works by doing a shallow, filtered fetch (git sparse-checkout) of
# just the paths we care about, so we never pull the whole upstream repo
# history or unrelated files. If nothing changed since the last run, it
# exits cleanly with no diff — the calling workflow decides whether to
# commit based on `git status`.

set -euo pipefail

# ---- configuration ---------------------------------------------------
UPSTREAM_REPO="${UPSTREAM_REPO:-MojoLauncher/freedreno_turnip-CI}"
UPSTREAM_BRANCH="${UPSTREAM_BRANCH:-main}"
UPSTREAM_URL="https://github.com/${UPSTREAM_REPO}.git"

# Paths (relative to upstream repo root) to mirror into vendor/upstream/.
# Add/remove lines here if MojoLauncher restructures their repo.
SYNC_PATHS=(
  "turnip_builder.sh"
  "LICENSE"
  "README.md"
  ".github"
)

DEST_DIR="vendor/upstream"
COMMIT_FILE="vendor/UPSTREAM_COMMIT.txt"
# -----------------------------------------------------------------------

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

echo "==> Fetching ${UPSTREAM_REPO}@${UPSTREAM_BRANCH} (sparse, shallow, no full clone)"

git -C "$WORKDIR" init -q
git -C "$WORKDIR" remote add origin "$UPSTREAM_URL"
git -C "$WORKDIR" config core.sparseCheckout true

# Only fetch the exact paths we want tracked, keeps this fast and avoids
# pulling any unrelated upstream source trees.
printf '%s\n' "${SYNC_PATHS[@]}" > "$WORKDIR/.git/info/sparse-checkout"

git -C "$WORKDIR" fetch --depth 1 origin "$UPSTREAM_BRANCH"
git -C "$WORKDIR" checkout -q FETCH_HEAD

UPSTREAM_SHA="$(git -C "$WORKDIR" rev-parse FETCH_HEAD)"
echo "==> Upstream commit: ${UPSTREAM_SHA}"

echo "==> Syncing tracked paths into ${DEST_DIR}/"
mkdir -p "$DEST_DIR"

# Remove anything currently in DEST_DIR that upstream no longer ships,
# then copy over the fresh sparse checkout. This keeps vendor/upstream/
# an exact mirror rather than an ever-growing pile.
find "$DEST_DIR" -mindepth 1 -maxdepth 1 -exec rm -rf {} +

for path in "${SYNC_PATHS[@]}"; do
  if [ -e "$WORKDIR/$path" ]; then
    mkdir -p "$DEST_DIR/$(dirname "$path")"
    cp -a "$WORKDIR/$path" "$DEST_DIR/$path"
  else
    echo "    (skip) upstream no longer has: $path"
  fi
done

mkdir -p "$(dirname "$COMMIT_FILE")"
cat > "$COMMIT_FILE" <<EOF
# Auto-generated by scripts/sync-upstream.sh — do not edit by hand.
upstream_repo=${UPSTREAM_REPO}
upstream_branch=${UPSTREAM_BRANCH}
upstream_commit=${UPSTREAM_SHA}
synced_at_utc=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF

echo "==> Done. Diff (if any) is now sitting in the working tree for the caller to commit."
